# See documentation at
# https://github.com/rust-lang/rust/blob/master/config.toml.example

[llvm]
link-shared = true

[build]
host = ["@triple@"]
target = ["@triple@"]
rustc = "@RUSTC@"
cargo = "@CARGO@" 

python = "python2.7"
extended = true
sanitizers = false

[install]
prefix = "@MAGISK_PREFIX@"
sysconfdir = "etc"

[rust]
codegen-units = 1

jemalloc = false

debuginfo = true
debuginfo-lines = true

channel = "stable"

rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config-8"


[target.@triple@]
android-ndk = "@MAGISK_STANDALONE_TOOLCHAIN@"
llvm-config = "@MAGISK_PREFIX@/bin/llvm-config"

[dist]
src-tarball = false
